### ISSUE TITLE
Feature request: pop()

### ISSUE THREAD

**Issue by beckend** [wyfo/swap-buffer-queue#14]
I would like to request a pop method, if possible pop_front and back.

**Comment by beckend** [comment]
And while I am at it, what about push, or is this kind of queue only everything or nothing?

**Comment by wyfo** [comment]
If I'm understanding correctly, popping a single element (assuming you use `ArrayBuffer`/`VecBuffer`) can be done using `BufferSlice::into_iter`, see [example](https://docs.rs/swap-buffer-queue/0.2.1/swap_buffer_queue/buffer/struct.OwnedBufferIter.html). "pop_back" is not supported by the algorithm, which is FIFO.

Regarding "push", I didn't really understand the question. What are you trying to achieve that `Queue::enqueue` can't?

**Comment by linkenquydinhhexagon** [comment]
I am not sure how this intended to work, it looks like `enqueue` takes a list of elements, `push` would take a single element.
So it's like all or nothing.
Because `.into_iter()` consumes.

**Comment by beckend** [comment]
I am not sure how this intended to work, it looks like enqueue takes a list of elements, push would take a single element.
So it's like all or nothing.
Because .into_iter() consumes.

**Comment by wyfo** [comment]
You can use `my_queue.enqueue([my_single_element])` (like in the example linked), and it will boil down to the same thing. I admit that the current API is not the best, and it should be possible to support both enqueuing single item and arrays of items — it's already in my drafts for the next version, among other things.

> Because .into_iter() consumes.

Can you develop? In the example linked, you can see that the buffer is requeued after `into_iter().next()`, so the next `into_iter().next()` will get the second item of the buffer.
However, the best way, in term of performance, to achieve one-by-one dequeuing is to use keep the iterator instead of calling `dequeue().unwrap().into_iter()` each time, which costs several atomics operations. This is what I've done in my [channel implementation](https://github.com/wyfo/crossbeam/blob/427b91b4eaa9f799a9887091f191446b361a4cbb/crossbeam-channel/benchmarks/channel.rs#L102) for benchmarking. 
It's indeed possible to implement a "classical" MPSC channel (with roughly the same API as crossbeam/tokio/etc.) using `swap-buffer-queue`, so you should be able to do a "pop". 

Keep in mind that `swap-buffer-queue` is a lower-level primitive than other MPSC channels. While `Queue::pop` could be possible to implement simply with `Ok(self.dequeue()?.into_iter().next())`, as explained above, this operation would not be very efficient, and it wouldn't have beat `crossbeam` with such implementation. 
That's why there is no `Queue::pop` equivalent, and why should use `Queue::dequeue`. And if you want to proceed items one by one, you can still use `BufferSlice::into_iter`.

Could you develop about your use case for which you would like to have `Queue::pop`? Isn't possible to use `BufferSlice::into_iter` instead? For example, this loop
```rust
while let Ok(item) = my_queue.pop() {
    // use item
}
````
could be rewritten with the more efficient version
```rust
while let Ok(slice) = my_queue.dequeue() {
    for item in slice {
        // use item
    }
}
```

**Comment by linkenquydinhhexagon** [comment]
Ok I did not get it that it would requeue itself if it's not exhausted, not a regular Vec for sure, thanks this gets me going.

**Comment by beckend** [comment]
Ok I did not get it that it would requeue itself if it's not exhausted, not a regular Vec for sure, thanks this gets me going.

**Comment by beckend** [comment]
I don't see this mentioned, how would I work with this queue in a multi threaded manner? Mutex?

**Comment by wyfo** [comment]
The queue is Multiple Producer Single Consumer (almost[^1]) lock-free. You can share it across multiple threads by wrapping it in an `Arc`, and use `Queue::enqueue` concurrently in all the threads, the same way you use classical channel `Sender` objects. Dequeuing on the other hand can only be done in a single thread. However, there is no special `Receiver` object, and you can use `Queue::dequeue` in any threads using your `Arc`. If you try to use it concurrently in multiple threads, only one will succeed and others will fail with `DequeueError::Conflict`. 
You should find some examples spawning threads in the documentation. But I agree the documentation needs to be improved.

[^1]: the algorithm only use atomic operations, but if a thread is abruptly stopped in the middle of the two-phase enqueueing, the queue will be kind of "blocked", as dequeuing will no more be possible. So it doesn't fully match the lock-free definition, more precisely the "Termination Safety" property. This is also the case for `crossbeam` for example.
